AllAlgorithms/python

- sorting/binary_search.py
Hello!  Here is my version of the binary search algorithm.
If you have any suggestions or spot any bugs, please let me know!
Thank you ^_^
Viva la Hacktoberfest!
> Add a binary search algorithm implementation

- searches/binary_search.py
- searches/linear_search.py
Added linear and binary search.
Resolves #2.
> feat(searches): add linear and binary search

- strings/palindrome.py
Added a palindrome algorithm for strings.
Resolves #2.
> feat(strings): add Palindrome algorithm

- sorting/insertion_sort.py
> Insertion Sort Added

- sorting/merge_sort.py
> Add mergesort

- sorting/quick_sort.py
> Created Quick Sort

- strings/anagram_search.py
- strings/morse_code.py
- strings/password_checker.py
- strings/rabin_karp.py
- 4 Programs for String algorithms (Password Checker, Morse Code, Rabin Karp algorithm, Anagram Search)
- As a part of #2 (Algorithm implementations in Python)
> 4 String Algorithms in Python

- sorting/radix_sort.py
- strings/anagram_search.py
- strings/morse_code.py
- strings/password_checker.py
- strings/rabin_karp.py
**Changes added** : Radix sort algorithm
> Radix sort

- sorting/bucket_sort.py
- strings/anagram_search.py
- strings/morse_code.py
- strings/password_checker.py
- strings/rabin_karp.py
Changes added : Bucket sort algorithm
> Bucket sort Algorithm in Python

- greedy/coin_change.py
- greedy/dijkstra_algo.py
- greedy/fractional_knapsack.py
- strings/anagram_search.py
- strings/morse_code.py
- strings/password_checker.py
- strings/rabin_karp.py
**Changes added** : Dijkstra's Algorithm, Coin Change Algorithm and Fractional Knapsack Algorithm using Greedy technique
> 3 Greedy Algorithms in Python

- sorting/heap_sort.py
i add a heap sort algorithm's python program
> add heap sort algorithm program in python

- searches/interpolation_search.py
- searches/ternary_search.py
- sorting/heap_sort.py
i add interpolation search algorithm using python
> Interpolation search

- strings/substring-check.py
Pros:
- faster
- more readable
> Use `in` for substring check

- graphs/breadth_first_search.py
Added python implementation for breadth first search
> Added python implementation for breadth first search

- graphs/breadth_first_search.py
- trees/lowest_common_ancestor.py
Added python implementation for lowest common ancestor
> Added python implementation for lowest common ancestor

- graphs/breadth_first_search.py
- trees/lowest_common_ancestor.py
- trees/min_height_bst.py
Added python implementation for creating a minimum height binary search tree, given a list of nodes
> Minimum Height Binary Search Tree

- strings/longest_substring.py
> Added an algorithm to find longest substring

- sorting/bogo_sort.py
If the goal is *all* algorithms, then bogo sort would need to get done eventually :)
> Add bogo sort implementation

- math/magic_square.py
- math/pascals_triangle.py
Magic Square algorithm Implemented. part of issue # 2
>  Added the magic square algorithm

- math/calcu_trig.py
calculation of trigonometric values
please let me know if there is the mistake in English
> add the calcu_trig_func algorithm

- sorting/counting_sort.py
This pull request is: 
This pull request fixes: #2 
**Changes:**
Added an in-place implementation of the Counting Sort algorithm
> Added Counting Sort

- cellular-automaton/conways_game_of_life.py
Hi there, here's a Game of Life implementation!
* Written for Python 3, tested with Python 3.7.0
* Module is executable and also importable.
* Supports converting a game board to and from a multiline string.
Here is a sample of the output of the glider example:
```
> python conways_game_of_life.py
Conway's Game of Life
Starting with seed: "Glider"
Running for 15 generations.
Generation 1:
··0····
0·0····
·00····
·······
·······
·······
Generation 2:
·0·····
··00···
·00····
·······
·······
·······
Generation 3: ...
```
> Implemented Conway's Game of Life with classic "glider" example

- math/lucky_numbers.py
Adds an implementation of an algorithm to generate the lucky numbers sequence.
#40
> Added the lucky numbers algorithm

- data-structures/stacks/node.py
- data-structures/stacks/stack.py
- data-structures/stacks/test_node.py
- data-structures/stacks/test_stack.py
I have done a stack to you, so you can include it into your data structures directory, It contains a stack module and a node module, and also contains its respectively unitary tests. :octocat: :star:
> Added stack to data structures and unitary tests

- linkedlist/middle_of_linkedlist.py
- trees/min_height_bst.py
Added python implementation for finding the middle element of a linkedlist.
> Added python implementation for finding the middle element of a linkedlist

- recursion/Coin-Change-Problem.py
Added coin change problem , I am not sure existing directory should be part of this solution so I have added new directory recursive
> Coin change problem in recursive way.

- math/gcd.py
Created python code for finding gcd in maths section.
> Created gcd.py

- strings/change_case.py
This algorithm will switch uppercase and lowercase characters much like the similar function found in `AllAlgorithms/c`.
Examples:
- `Hello, world!` -> `hELLO, WORLD!`
- `TEST` -> `test`
> Added algorithm that switches the case of strings

- math/Sieve of Eratosthenes.py
Added algorithm for sieve of eratosthenes
> Sieve of eratosthenes

- graphs/Bron-Kerbosch.py
added a simple Version from the Bronk-Kerbosch Algorithm to the graph Directory.
> Added Bron-Kerbosch Algorithm for finding cliques

- linkedlist/middle_of_linkedlist.py
- linkedlist/reverse_linkedlist.py
- trees/min_height_bst.py
Python implementation for recursively reversing a linkedlist.
> Python implementation for recursively reversing a linkedlist

- dynamic-programming/matrix_chain_multiplication.py
Added Matrix Chain Multiplication in Python
> Added Matrix Chain Multiplication in Python

- strings/word_length_dict.py
Example Output:
`{'The': 3, 'quick': 5, 'brown': 5, 'fox': 3, 'jumps': 5, 'over': 4, 'the': 3, 'lazy': 4, 'dog': 3}`
> Function to add all words of a string as key and its length as value to a dict

- algorithms/math/SieveOfEratosthenes.py
I'm new to this, so do let me know if I'm doing this right.
- [Y] New algorithm
- [N] Update to an algorithm
- [N] Fix an error
- [N] Other - *Describe below*
> Adding Sieve Of Eratosthenes to algorithms->math

- math/armstrong_number.py
I am creating a pull request for Armstrong Number
> Added Armstrong Number

- math/factorial.py
I am creating a pull request for factorial program.
> added factorial program

- algorithms/data-structures/trees/size_of_subtree.py
- [ Size of subtree ] New algorithm
> Added Subtree Size

- algorithms/cryptography/Hill_cipher.py
> Added implementation of Hill cipher In python

- data-structures/binarySerach.py
- data-structures/linked-lists/singleLinkedModule.py
> new algorithm 

- algorithms/recursion/Factorial By Recursion Python.py
>  Factorial By Recursion in Python

- data-structures/Array Intersection.py
the code will Help the user to find same elements in given two arrays by the user.
Thank You!!
> Added New Data-Structure program

- algorithms/recursion/exponentiation.py
> Added recursive optimized exponetiation algorithm.

- algorithms/strings/levenstein.py
> add algorithm for calculating Levenshtein Distance

- algorithms/recursion/exponentiation.py
> Making the algorithm work for 0 and negative int power values

- data-structures/linked-lists/is_palindrome.py
> added is_palindrome for linked list

- algorithms/sorting/cocktail_sort.py
> add cocktail_sort

- algorithms/cryptography/Hill_cipher.py
- algorithms/cryptography/railfence_cipher.py
> Rail Fence cipher in python

- classification/fcm.py
- classification/tools.py
> added a classification algorithms folder
